name: Check UTF-8 Encoding

on: [push, pull_request]

jobs:
  check-encoding:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check file encodings
        run: |
          bad=$(find . -type f ! -path "./.git/*" -exec file -i {} \; | grep -v "utf-8" | grep -v "us-ascii" || true)
          if [ -n "$bad" ]; then
            echo "❌ Nicht-UTF-8 Dateien gefunden:"
            echo "$bad"
            exit 1
          fi
